/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Marlabs.Main;

import Marlabs.Constants.Constants;
import static Marlabs.Core.BaseClass.excel;
import java.awt.Toolkit;

/**
 *
 * @author govardhanar
 */
public class FrameRegression extends javax.swing.JFrame {

    /**
     * Creates new form FrameRegression
     */
    public FrameRegression() {
        initComponents();
        SetIcon();
    }
    
    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logo_16x16.png"))); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        chkLogin = new javax.swing.JCheckBox();
        chkAddRemoveDeal = new javax.swing.JCheckBox();
        chkAddEditDeal = new javax.swing.JCheckBox();
        chkWeeklyAds = new javax.swing.JCheckBox();
        btnRegressionOk = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Regression Suite");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Please select the Test Cases for Regression");

        chkLogin.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        chkLogin.setText("Login");

        chkAddRemoveDeal.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        chkAddRemoveDeal.setText("Add_Remove_Deal");

        chkAddEditDeal.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        chkAddEditDeal.setText("Add_Edit_Deal");

        chkWeeklyAds.setFont(new java.awt.Font("Calibri", 0, 16)); // NOI18N
        chkWeeklyAds.setText("WeeklyAds");

        btnRegressionOk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnRegressionOk.setText("OK");
        btnRegressionOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegressionOkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkLogin)
                            .addComponent(chkWeeklyAds)
                            .addComponent(chkAddRemoveDeal)
                            .addComponent(chkAddEditDeal))))
                .addContainerGap(120, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegressionOk, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(chkLogin)
                .addGap(18, 18, 18)
                .addComponent(chkAddRemoveDeal)
                .addGap(18, 18, 18)
                .addComponent(chkAddEditDeal)
                .addGap(18, 18, 18)
                .addComponent(chkWeeklyAds)
                .addGap(18, 18, 18)
                .addComponent(btnRegressionOk)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegressionOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegressionOkActionPerformed
	
        Constants.FlaggedTCs.clear();
        
        if(chkLogin.isSelected())
            Constants.FlaggedTCs.add(chkLogin.getText());
	
        if(chkAddRemoveDeal.isSelected())
            Constants.FlaggedTCs.add(chkAddRemoveDeal.getText());
        
        if(chkAddEditDeal.isSelected())
            Constants.FlaggedTCs.add(chkAddEditDeal.getText());
        
        if(chkWeeklyAds.isSelected())
            Constants.FlaggedTCs.add(chkWeeklyAds.getText());
        
        this.setVisible(false);
    }//GEN-LAST:event_btnRegressionOkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameRegression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameRegression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameRegression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameRegression.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameRegression().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegressionOk;
    private javax.swing.JCheckBox chkAddEditDeal;
    private javax.swing.JCheckBox chkAddRemoveDeal;
    private javax.swing.JCheckBox chkLogin;
    private javax.swing.JCheckBox chkWeeklyAds;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
