/*
 * 7753941893 To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Marlabs.Main;

import Marlabs.Constants.Constants;
import Marlabs.Core.Xls_Reader;
import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.ListModel;

/**
 *
 * @author govardhanar
 */
public class FrameMobile extends javax.swing.JFrame {

    /**
     * Creates new form FrameMobile
     */
    public FrameMobile() {
        initComponents();
        SetIcon();
       
    }
    
    private void SetIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Images/logo_16x16.png"))); 
    }
    
    static DefaultListModel sort(DefaultListModel dlm) { 
        Object [] dlma = dlm.toArray();   
        Arrays.sort(dlma);  
        dlm.clear();   
        for (Object x : dlma)
            dlm.addElement(x);   
        
        return dlm;
    }
    
    public void LoadTestCases()
    {
       String  suiteName = Constants.MobileSuiteName;
       String  path = Constants.MobileTestSuite;
       String  sheetName = Constants.MobileSuiteSheetName;
      
        Xls_Reader excel = new Xls_Reader(path);
        int cellId = 2;
        String cellData = "";
        
        DefaultListModel mTestCases = new DefaultListModel();
        DefaultListModel mTestCasesR = new DefaultListModel();
        lstMTestCasesRight.setModel(mTestCasesR);
        while(true)
        {
           cellData = (String) excel.getCellData(sheetName, 0, cellId);
         
           if(cellData.trim().length() > 0)
           {
               mTestCases.addElement(cellData); 
               cellId++;
           }
           else
               break;
        }
        
        lstMTestCasesLeft.setModel(sort(mTestCases));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        chkLogin = new javax.swing.JCheckBox();
        chkAddRemoveDeal = new javax.swing.JCheckBox();
        chkAddEditDeal = new javax.swing.JCheckBox();
        chkWeeklyAds = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        btnMobileOK = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnTCMoveRight = new javax.swing.JButton();
        btnTCMoveLeft = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMTestCasesRight = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstMTestCasesLeft = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Select Mobile Test Cases");

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setTitle("Mobile Test Suite");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Please select the Test Cases for Mobile Test");

        chkLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkLogin.setText("Login");

        chkAddRemoveDeal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkAddRemoveDeal.setText("Add_Remove_Deal");

        chkAddEditDeal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkAddEditDeal.setText("Add_Edit_Deal");

        chkWeeklyAds.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chkWeeklyAds.setText("WeeklyAds");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkLogin)
                            .addComponent(chkWeeklyAds)
                            .addComponent(chkAddRemoveDeal)
                            .addComponent(chkAddEditDeal))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(chkLogin)
                .addGap(18, 18, 18)
                .addComponent(chkAddRemoveDeal)
                .addGap(18, 18, 18)
                .addComponent(chkAddEditDeal)
                .addGap(18, 18, 18)
                .addComponent(chkWeeklyAds)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Please select the Test Cases for Mobile Test");

        btnMobileOK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnMobileOK.setText("OK");
        btnMobileOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMobileOKActionPerformed(evt);
            }
        });

        jLabel3.setText("Available Cases");

        btnTCMoveRight.setText(">>");
        btnTCMoveRight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTCMoveRightActionPerformed(evt);
            }
        });

        btnTCMoveLeft.setText("<<");
        btnTCMoveLeft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTCMoveLeftActionPerformed(evt);
            }
        });

        jLabel4.setText("Selected Cases");

        lstMTestCasesRight.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstMTestCasesRightMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstMTestCasesRight);

        lstMTestCasesLeft.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstMTestCasesLeftMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lstMTestCasesLeft);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMobileOK, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTCMoveRight)
                                    .addComponent(btnTCMoveLeft))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel2))))
                .addGap(31, 31, 31))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 235, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 235, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jLabel3)
                    .addContainerGap(372, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(btnTCMoveRight)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTCMoveLeft))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(10, 10, 10)
                .addComponent(btnMobileOK)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 178, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 179, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(69, 69, 69)
                    .addComponent(jLabel3)
                    .addContainerGap(274, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMobileOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobileOKActionPerformed

    	Constants.MobileFlaggedTCs.clear();
        
        ListModel rightLM = this.lstMTestCasesRight.getModel();    	
    	
    	for(int i=0;i<rightLM.getSize();i++){             
    		Constants.MobileFlaggedTCs.add(rightLM.getElementAt(i).toString());          
         }  	   	
    	
        this.setVisible(false);
              
    }//GEN-LAST:event_btnMobileOKActionPerformed

    private void btnTCMoveRightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTCMoveRightActionPerformed

        ListModel leftLM = lstMTestCasesLeft.getModel();
        ListModel rightLM = lstMTestCasesRight.getModel();

        DefaultListModel leftDLM = new DefaultListModel();  
        DefaultListModel rightDLM = new DefaultListModel(); 

        for(int i=0;i<leftLM.getSize();i++){
            if(lstMTestCasesLeft.isSelectedIndex(i)){  
                rightDLM.addElement(leftLM.getElementAt(i));
            }//if
            else{
                leftDLM.addElement(leftLM.getElementAt(i)); 
            }//else
        }//for
        lstMTestCasesLeft.setModel(leftDLM); 
        System.out.println(leftDLM); 

        for(int i=0;i<rightLM.getSize();i++){
            rightDLM.addElement(rightLM.getElementAt(i));
        }

        lstMTestCasesRight.setModel(rightDLM);

        lstMTestCasesLeft.clearSelection();
        lstMTestCasesLeft.clearSelection();
    }//GEN-LAST:event_btnTCMoveRightActionPerformed

    private void btnTCMoveLeftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTCMoveLeftActionPerformed

        //get access through interface ListModel to left and Right JLists's models
        ListModel leftLM = lstMTestCasesLeft.getModel();
        ListModel rightLM = lstMTestCasesRight.getModel();

        DefaultListModel leftDLM = new DefaultListModel();  //Create new instance of DefaultListModel for left JList
        DefaultListModel rightDLM = new DefaultListModel(); //Create new instance of DefaultListModel for right JList

        //copy existing items to DefaultListModel
        for(int i=0;i<rightLM.getSize();i++){
            if(lstMTestCasesRight.isSelectedIndex(i)){  //but we have to skip selected item
                leftDLM.addElement(rightLM.getElementAt(i));
            }//if
            else{
                rightDLM.addElement(rightLM.getElementAt(i)); //element added
            }//else
        }//for
        lstMTestCasesRight.setModel(rightDLM);//set new model for left JList without "deleted" item
        //System.out.println(leftDLM);//let's print it and see the new model

        //copy items from right ListModel to new DefaultListModel
        for(int i=0;i<leftLM.getSize();i++){
            leftDLM.addElement(leftLM.getElementAt(i));
        }

        lstMTestCasesLeft.setModel(leftDLM);

        lstMTestCasesLeft.clearSelection();
        lstMTestCasesLeft.clearSelection();
    }//GEN-LAST:event_btnTCMoveLeftActionPerformed

    private void lstMTestCasesRightMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstMTestCasesRightMouseClicked
       JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            if (index >= 0) {
                Object selItem = list.getModel().getElementAt(index);
                ((DefaultListModel) lstMTestCasesLeft.getModel()).addElement(selItem);
                ((DefaultListModel) lstMTestCasesRight.getModel()).removeElement(selItem);
             }
        }
    }//GEN-LAST:event_lstMTestCasesRightMouseClicked

    private void lstMTestCasesLeftMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstMTestCasesLeftMouseClicked
         JList list = (JList)evt.getSource();
        if (evt.getClickCount() == 2) {
            int index = list.locationToIndex(evt.getPoint());
            if (index >= 0) {
                Object selItem = list.getModel().getElementAt(index);
                ((DefaultListModel) lstMTestCasesRight.getModel()).addElement(selItem);
                ((DefaultListModel) lstMTestCasesLeft.getModel()).removeElement(selItem);
            }
        }
    }//GEN-LAST:event_lstMTestCasesLeftMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMobile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMobileOK;
    private javax.swing.JButton btnTCMoveLeft;
    private javax.swing.JButton btnTCMoveRight;
    private javax.swing.JCheckBox chkAddEditDeal;
    private javax.swing.JCheckBox chkAddRemoveDeal;
    private javax.swing.JCheckBox chkLogin;
    private javax.swing.JCheckBox chkWeeklyAds;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList lstMTestCasesLeft;
    private javax.swing.JList lstMTestCasesRight;
    // End of variables declaration//GEN-END:variables
}
